services:
  commander:
    build:
      context: ./
      dockerfile: Dockerfile.commander
    ports:
      - 8080:8080
    init: true
    command: ["sleep", "infinity"]

  agents:
    build:
      context: ./
      dockerfile: Dockerfile.agent
    deploy:
      replicas: 3
    init: true
    command: ["sleep", "infinity"]
