services:
  commander:
    build:
      context: ./
    user: root
    init: true
    command: ["sleep", "infinity"]

  agents:
    image: ubuntu:22.04
    deploy:
      replicas: 3
    user: root
    init: true
    command: ["sleep", "infinity"]
