services:
  commander:
    build:
      context: ./
      dockerfile: Dockerfile.commander
    init: true
    command: ["sleep", "infinity"]

  agents:
    build:
      context: ./
      dockerfile: Dockerfile.agent
    deploy:
      replicas: 3
    user: root
    init: true
    command: ["sleep", "infinity"]
