services:
  commander:
    build:
      context: ./
      dockerfile: commander.Dockerfile
    ports:
      - 8080:8080
    init: true
    command: ["sleep", "infinity"]

  agents:
    build:
      context: ./
      dockerfile: agent.Dockerfile
    deploy:
      replicas: 3
    init: true
    command: ["/usr/sbin/sshd", "-D"]
