services:
  commander:
    image: ubuntu:22.04
    init: true
    command: ["sleep", "infinity"]

  agents:
    image: ubuntu:22.04
    deploy:
      replicas: 3
    init: true
    command: ["sleep", "infinity"]
