---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - openjdk-17-jdk
      - gnupg2
      - curl
    state: present
    update_cache: yes

- name: Add jenkins repository key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc

- name: Add jenkins apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start jenkins in the background (no systemd)
  shell: |
    nohup java \
    -Djenkins.model.Jenkins.slaveAgentPort=8081 \
    -jar /usr/share/java/jenkins.war \
    --httpListenAddress=0.0.0.0 \
    --httpPort=8080 > /var/log/jenkins.log 2>&1 & echo $! > /var/run/jenkins.pid

- name: Wait for Jenkins to be fully available via HTTP API
  uri:
    url: http://localhost:8080/login
    status_code: 200
  register: jenkins_service_status
  until: >
    'status' in jenkins_service_status and
    jenkins_service_status.status == 200

- name: Set Jenkins admin password as a global fact
  set_fact:
    jenkins_admin_password: "{{ lookup('file', '/root/.jenkins/secrets/initialAdminPassword') }}"

- name: Install jenkins plugins
  jenkins_plugin:
    name: swarm
    url: http://localhost:8080
    url_username: admin
    url_password: "{{ jenkins_admin_password }}"
