---
- name: Confirm connection to commander and agents
  hosts: all
  tasks:
    - name: Get ip address
      shell: |
        getent ahostsv4 {{ inventory_hostname }} | grep STREAM | head -n 1 | awk '{print $1}'
      register: internal_ip_command

    - name: Say hello
      debug:
        msg: "The internal IP address of {{ inventory_hostname }} is {{ internal_ip_command.stdout }}"
