---
- name: Set up jenkins commander
  hosts: commander
  roles:
    - role: debug
    - role: jenkins_commander

- name: Set up jenkins agents
  hosts: agents
  roles:
    - role: debug
    - role: jenkins_agent
      vars:
        jenkins_admin_password: "{{ hostvars['ansible-jenkins-commander-1'].jenkins_admin_password }}"
