---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - openjdk-17-jdk
    state: present
    update_cache: yes

- name: Download jenkins swarm client
  get_url:
    url: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.25/swarm-client-3.25.jar
    dest: /root/swarm-client.jar

- name: Register agent with jenkins master
  shell: |
    nohup java -jar /root/swarm-client.jar \
    -master http://commander:8080 \
    -name "{{ inventory_hostname }}" \
    -labels "agent" \
    -executors 1 > /root/swarm-client.log 2>&1 &
